// Command charrnn trains a character-level LSTM on a small embedded corpus
// and generates text from it. It exercises the autograd side of tensai:
// LSTMCell, Trainer (backpropagation through time over an unrolled loop),
// and SaveParams/LoadParams.
package main

import (
	"fmt"
	"math/rand"
	"os"
	"strings"

	tensai "github.com/mattn/tensai"
	"github.com/mattn/tensai/autograd"
	"github.com/mattn/tensai/optim"
	"github.com/mattn/tensai/rnn"
)

const (
	hidden    = 96
	seqLen    = 32
	batchSize = 16
	iters     = 400
	seed      = 7
	paramFile = "charrnn.json"
)

type charModel struct {
	cell       *rnn.LSTMCell
	wOut, bOut *autograd.Node
	vocab      []rune
	index      map[rune]int
}

func newCharModel(vocab []rune, rng *rand.Rand) *charModel {
	m := &charModel{
		cell:  rnn.NewLSTMCell(len(vocab), hidden, rng),
		wOut:  autograd.Param(tensai.RandomMatrix(hidden, len(vocab), rng)),
		bOut:  autograd.Param(tensai.NewMatrix(1, len(vocab))),
		vocab: vocab,
		index: make(map[rune]int, len(vocab)),
	}
	for i, r := range vocab {
		m.index[r] = i
	}
	return m
}

func (m *charModel) params() []*autograd.Node {
	return append(m.cell.Params(), m.wOut, m.bOut)
}

// step feeds one time step and returns (logits, hidden, cell).
func (m *charModel) step(x, h, c *autograd.Node) (*autograd.Node, *autograd.Node, *autograd.Node) {
	h, c = m.cell.Step(x, h, c)
	return h.MatMul(m.wOut).AddRow(m.bOut), h, c
}

// oneHot encodes text[pos[i]+t] for each batch row i.
func (m *charModel) oneHot(text []rune, pos []int, t int) *tensai.Matrix {
	x := tensai.NewMatrix(len(pos), len(m.vocab))
	for i, p := range pos {
		x.Data[i*len(m.vocab)+m.index[text[p+t]]] = 1
	}
	return x
}

// loss builds the unrolled training graph for one batch of subsequences:
// at every step the model predicts the next character.
func (m *charModel) loss(text []rune, pos []int) *autograd.Node {
	h, c := m.cell.InitState(len(pos))
	var total *autograd.Node
	for t := 0; t < seqLen; t++ {
		logits, hn, cn := m.step(autograd.Input(m.oneHot(text, pos, t)), h, c)
		h, c = hn, cn
		targets := tensai.NewMatrix(len(pos), 1)
		for i, p := range pos {
			targets.Data[i] = float32(m.index[text[p+t+1]])
		}
		l := logits.SoftmaxCELoss(targets)
		if total == nil {
			total = l
		} else {
			total = total.Add(l)
		}
	}
	return total.Scale(1.0 / seqLen)
}

// generate samples n characters starting from the given prefix.
func (m *charModel) generate(prefix string, n int, temperature float32, rng *rand.Rand) string {
	var sb strings.Builder
	sb.WriteString(prefix)
	h, c := m.cell.InitState(1)
	var logits *autograd.Node
	feed := func(r rune) {
		x := tensai.NewMatrix(1, len(m.vocab))
		x.Data[m.index[r]] = 1
		logits, h, c = m.step(autograd.Input(x), h, c)
	}
	for _, r := range prefix {
		feed(r)
	}
	for i := 0; i < n; i++ {
		probs := logits.Scale(1 / temperature).Softmax().Value
		r := m.vocab[sample(probs.Data, rng)]
		sb.WriteRune(r)
		feed(r)
	}
	return sb.String()
}

// sample draws an index from a probability distribution.
func sample(probs []float32, rng *rand.Rand) int {
	x := float32(rng.Float64())
	for i, p := range probs {
		x -= p
		if x <= 0 {
			return i
		}
	}
	return len(probs) - 1
}

func vocabOf(text []rune) []rune {
	seen := map[rune]bool{}
	var vocab []rune
	for _, r := range text {
		if !seen[r] {
			seen[r] = true
			vocab = append(vocab, r)
		}
	}
	return vocab
}

func main() {
	text := []rune(corpus)
	vocab := vocabOf(text)
	fmt.Printf("corpus: %d chars, vocab: %d\n", len(text), len(vocab))

	rng := rand.New(rand.NewSource(seed))
	model := newCharModel(vocab, rng)
	trainer := autograd.NewTrainer(optim.NewAdam(0.01), model.params()...)

	for it := 1; it <= iters; it++ {
		pos := make([]int, batchSize)
		for i := range pos {
			pos[i] = rng.Intn(len(text) - seqLen - 1)
		}
		lossVal := trainer.Step(model.loss(text, pos))
		if it == 1 || it%50 == 0 {
			fmt.Printf("iter %4d: loss=%.4f\n", it, lossVal)
		}
	}

	// Save the trained parameters, then restore them into a fresh model to
	// demonstrate the round trip; generation runs on the reloaded model.
	if err := autograd.SaveParamsFile(paramFile, model.params()...); err != nil {
		fmt.Fprintf(os.Stderr, "charrnn: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("parameters saved to %s\n", paramFile)

	reloaded := newCharModel(vocab, rand.New(rand.NewSource(seed+1)))
	if err := autograd.LoadParamsFile(paramFile, reloaded.params()...); err != nil {
		fmt.Fprintf(os.Stderr, "charrnn: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("\ngenerated by the reloaded model:")
	fmt.Println(reloaded.generate("Alice ", 400, 0.7, rand.New(rand.NewSource(seed+2))))
}

// The opening of "Alice's Adventures in Wonderland" by Lewis Carroll
// (public domain).
const corpus = `Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, "and what is the use of a book," thought Alice "without pictures or conversations?"

So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.

There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, "Oh dear! Oh dear! I shall be late!" (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.

In another moment down went Alice after it, never once considering how in the world she was to get out again.

The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.

Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled "ORANGE MARMALADE", but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody underneath, so managed to put it into one of the cupboards as she fell past it.

"Well!" thought Alice to herself, "after such a fall as this, I shall think nothing of tumbling down stairs! How brave they'll all think me at home! Why, I wouldn't say anything about it, even if I fell off the top of the house!" (Which was very likely true.)`
