package qwenimage

import (
	"encoding/binary"
	"fmt"
	"image/png"
	"math"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/mattn/tensai"
)

func TestDupUpChannelMapping(t *testing.T) {
	for _, stage := range stages {
		if !stage.up {
			continue
		}
		t.Run(fmt.Sprintf("%d_%d_%t", stage.in, stage.out, stage.temporal), func(t *testing.T) {
			const h, w = 3, 5
			factorT := 1
			if stage.temporal {
				factorT = 2
			}
			repeat := stage.out * factorT * 4 / stage.in
			x := tensai.NewMatrix(h*w, stage.in)
			for i := range x.Data {
				x.Data[i] = tensai.Float(i)
			}
			got := dupUp(x, h, w, stage.out, repeat, factorT)
			for y := 0; y < 2*h; y++ {
				for px := 0; px < 2*w; px++ {
					for oc := 0; oc < stage.out; oc++ {
						ic := (((oc*factorT+factorT-1)*2+y%2)*2 + px%2) / repeat
						want := x.Data[((y/2)*w+px/2)*stage.in+ic]
						if got.Data[(y*2*w+px)*stage.out+oc] != want {
							t.Fatalf("pixel (%d,%d), channel %d: incorrect shuffle", y, px, oc)
						}
					}
				}
			}
		})
	}
}

// vaeDir is where the checkpoint's vae/ directory is expected. The test
// skips without it: the weights are 1.3 GB and are not in the repo.
func vaeDir(t *testing.T) string {
	t.Helper()
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skip(err)
	}
	dir := filepath.Join(home, ".cache", "tensai", "Qwen-Image-2.1", "vae")
	if _, err := os.Stat(filepath.Join(dir, "diffusion_pytorch_model.safetensors")); err != nil {
		t.Skipf("no VAE checkpoint under %s", dir)
	}
	return dir
}

// readF32 reads a little-endian float32 dump, the form the reference
// script writes its tensors in.
func readF32(t *testing.T, path string, want int) []tensai.Float {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("no reference dump: %v", err)
	}
	if len(b) != 4*want {
		t.Fatalf("%s: %d bytes, want %d floats", path, len(b), want)
	}
	out := make([]tensai.Float, want)
	for i := range out {
		out[i] = math.Float32frombits(binary.LittleEndian.Uint32(b[4*i:]))
	}
	return out
}

// TestDecodeMatchesReference decodes the latent that testdata/gen.py fed
// to diffusers and compares every sample against what diffusers
// produced. The dumps are generated by hand (see testdata/gen.py); the
// test skips when they are absent.
func TestDecodeMatchesReference(t *testing.T) {
	dir := vaeDir(t)
	const latent = 16 // 16x16 latent, a 256x256 image
	z := tensai.NewTensor(64, latent, latent)
	copy(z.Data, readF32(t, filepath.Join("testdata", "latent_16.f32"), len(z.Data)))
	want := readF32(t, filepath.Join("testdata", "decoded_16.f32"), 4*16*latent*16*latent)

	d, err := LoadDecoder(filepath.Join(dir, "diffusion_pytorch_model.safetensors"))
	if err != nil {
		t.Fatal(err)
	}
	got, err := Decode(d, z)
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Data) != len(want) {
		t.Fatalf("decoded %d samples, reference has %d", len(got.Data), len(want))
	}
	// float32 convolutions this deep drift a little against torch's own
	// order of operations, so the bar is a visible difference: 1/255 is
	// one step of an 8-bit channel over the [-1,1] range.
	var worst float64
	var at int
	for i, w := range want {
		if d := math.Abs(float64(got.Data[i] - w)); d > worst {
			worst, at = d, i
		}
	}
	t.Logf("largest difference %.6f at sample %d", worst, at)
	if worst > 2.0/255 {
		t.Errorf("decoded sample %d is %.6f, reference %.6f", at, got.Data[at], want[at])
	}
}

// TestDecodeWritesPNG decodes the reference latent and writes it where
// TENSAI_VAE_PNG points, so the decoder's output can be looked at rather
// than only measured.
func TestDecodeWritesPNG(t *testing.T) {
	out := os.Getenv("TENSAI_VAE_PNG")
	if out == "" {
		t.Skip("set TENSAI_VAE_PNG to a path to write the decoded image")
	}
	dir := vaeDir(t)
	const latent = 16
	z := tensai.NewTensor(64, latent, latent)
	copy(z.Data, readF32(t, filepath.Join("testdata", "latent_16.f32"), len(z.Data)))

	d, err := LoadDecoder(filepath.Join(dir, "diffusion_pytorch_model.safetensors"))
	if err != nil {
		t.Fatal(err)
	}
	start := time.Now()
	got, err := Decode(d, z)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("decoded %dx%d in %v", latent*16, latent*16, time.Since(start).Round(time.Millisecond))
	img, err := Image(got)
	if err != nil {
		t.Fatal(err)
	}
	f, err := os.Create(out)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if err := png.Encode(f, img); err != nil {
		t.Fatal(err)
	}
}
